name = "Meteor-Fatpack"
author = "mrkeww"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87b4d096de6bc3a51a0491449f4367d39a2b168ff804453ebabef5b6137ba9eb"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
