name = "Meteor Fatpack"
author = "mrkeww"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "508b93ba0ca6d0e435fa7eb30cc0c2ebcd2984e6419599e54b9c733d2fc751fb"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
