name = "Meteor-Fatpack"
author = "mrkeww"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb1b4cd9c9cbca4b9e9b2097e27be988ec8fc778d6ef9cb3965dcc3bc1ffd090"

[versions]
fabric = "0.14.23"
minecraft = "1.20.2"
